# NeRF

In [ ]:
!rm -rf '/content/cg_nerf/'
!git clone https://github.com/LazyGH/cg_nerf.git
%cd /content/cg_nerf
# %pip install -U imageio imageio-ffmpeg scipy matplotlib lpips configargparse tensorboard

# !sed -i 's/archive.ubuntu.com/us-central1.gce.archive.ubuntu.com/g' /etc/apt/sources.list
# !apt-get update -y
# !apt-get install -y imagemagick

%pip install -q condacolab
import condacolab
condacolab.install()

%cd /content/cg_nerf
!mamba env create -f nerf/environment_colab_tf115.yml
!conda run -n nerf-tf115 python -V

%cd /content/cg_nerf/nerf
!conda run -n nerf-tf115 bash download_example_data.sh > /dev/null

Streaming output truncated to the last 5000 lines.
111950K .......... .......... .......... .......... .......... 30% 1.83M 57s
112000K .......... .......... .......... .......... .......... 30%  211M 57s
112050K .......... .......... .......... .......... .......... 30% 1.83M 57s
112100K .......... .......... .......... .......... .......... 31%  279M 57s
112150K .......... .......... .......... .......... .......... 31% 1.82M 57s
112200K .......... .......... .......... .......... .......... 31%  248M 57s
112250K .......... .......... .......... .......... .......... 31%  319M 57s
112300K .......... .......... .......... .......... .......... 31% 1.83M 57s
112350K .......... .......... .......... .......... .......... 31%  203M 57s
112400K .......... .......... .......... .......... .......... 31% 1.83M 57s
112450K .......... .......... .......... .......... .......... 31%  212M 57s
112500K .......... .......... .......... .......... .......... 31% 1.84M 57s
112550K .......... ......

Train test

In [ ]:
%cd /content/cg_nerf/nerf
!time conda run -n nerf-tf115 python run_nerf.py --config course_configs/lego_t4_test.txt

/content/cg_nerf/nerf
Fixing random seed 0
Loaded blender (138, 400, 400, 4) (40, 4, 4) [400, 400, 555.5555155968841] ./data/nerf_synthetic/lego
MODEL 63 27 <class 'int'> <class 'int'> True
(?, 90) (?, 63) (?, 27)
MODEL 63 27 <class 'int'> <class 'int'> True
(?, 90) (?, 63) (?, 27)
Not ndc!
Found ckpts []
Begin
TRAIN views are [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]
TEST views are [113 114 115 116 117 118 119 120 121 122 123 124 125 126 127 128 129 130
 131 132 133 134 135 136 137]
VAL views are [100 101 102 103 104 105 106 107 108 109 110 111 112]
precrop 100 100 tf.Tensor([100 100], shape=(2,), dtype=int32) tf.Tensor([299 299], shape=(2,), dtype=int32)
saved weights at ./logs/lego_t4_20min/model_000000.npy
saved weights at

Train NeRF Lego

In [ ]:
%cd /content/cg_nerf/nerf
!time conda run -n nerf-tf115 python run_nerf.py --config course_configs/lego_t4_20min.txt

/content/cg_nerf/nerf
Fixing random seed 0
Loaded blender (138, 400, 400, 4) (40, 4, 4) [400, 400, 555.5555155968841] ./data/nerf_synthetic/lego
MODEL 63 27 <class 'int'> <class 'int'> True
(?, 90) (?, 63) (?, 27)
MODEL 63 27 <class 'int'> <class 'int'> True
(?, 90) (?, 63) (?, 27)
Not ndc!
Found ckpts []
Begin
TRAIN views are [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]
TEST views are [113 114 115 116 117 118 119 120 121 122 123 124 125 126 127 128 129 130
 131 132 133 134 135 136 137]
VAL views are [100 101 102 103 104 105 106 107 108 109 110 111 112]
precrop 100 100 tf.Tensor([100 100], shape=(2,), dtype=int32) tf.Tensor([299 299], shape=(2,), dtype=int32)
saved weights at ./logs/lego_t4_20min/model_000000.npy
saved weights at

In [ ]:
%cd /content/cg_nerf/nerf
!time conda run -n nerf-tf115 python run_nerf.py --config course_configs/lego_t4_30min.txt

/content/cg_nerf/nerf

CondaError: KeyboardInterrupt


real	29m2.488s
user	0m0.312s
sys	0m0.053s


Train NeRF Fern

In [ ]:
%cd /content/cg_nerf/nerf
!time conda run -n nerf-tf115 python run_nerf.py --config course_configs/fern_t4_20min.txt

/content/cg_nerf/nerf
Fixing random seed 0
Loaded image data (378, 504, 3, 20) [378.         504.         407.56579161]
Loaded ./data/nerf_llff_data/fern 16.985296178676084 80.00209740336334
recentered (3, 5)
[[ 1.0000000e+00  0.0000000e+00  0.0000000e+00  1.4901161e-09]
 [ 0.0000000e+00  1.0000000e+00 -1.8730975e-09 -9.6857544e-09]
 [-0.0000000e+00  1.8730975e-09  1.0000000e+00  0.0000000e+00]]
Data:
(20, 3, 5) (20, 378, 504, 3) (20, 2)
HOLDOUT view is 12
Loaded llff (20, 378, 504, 3) (120, 3, 5) [378.     504.     407.5658] ./data/nerf_llff_data/fern
Auto LLFF holdout, 8
DEFINING BOUNDS
NEAR FAR 0.0 1.0
MODEL 63 27 <class 'int'> <class 'int'> True
(?, 90) (?, 63) (?, 27)
MODEL 63 27 <class 'int'> <class 'int'> True
(?, 90) (?, 63) (?, 27)
Found ckpts []
get rays
done, concats
shuffle rays
done
Begin
TRAIN views are [ 1  2  3  4  5  6  7  9 10 11 12 13 14 15 17 18 19]
TEST views are [ 0  8 16]
VAL views are [ 0  8 16]
saved weights at ./logs/fern_t4_20min/model_000000.npy
saved weight

Tensorboard

In [ ]:
%load_ext tensorboard
%tensorboard --logdir /content/cg_nerf/nerf/logs/summaries

NeRF Evaluation

Trained Lego

In [ ]:
%cd /content/cg_nerf
!conda run -n nerf-tf115 python project_tools/render_eval_nerf.py --config nerf/course_configs/lego_t4_20min.txt --output_dir result/nerf/lego_trained --source trained --train_time_minutes 20

/content/cg_nerf
MODEL 63 27 <class 'int'> <class 'int'> True
(?, 90) (?, 63) (?, 27)
MODEL 63 27 <class 'int'> <class 'int'> True
(?, 90) (?, 63) (?, 27)
Not ndc!
Found ckpts ['/content/cg_nerf/nerf/logs/lego_t4_20min/model_005000.npy']
Reloading from /content/cg_nerf/nerf/logs/lego_t4_20min/model_005000.npy
Resetting step to 5001
Reloading fine from /content/cg_nerf/nerf/logs/lego_t4_20min/model_fine_005000.npy
Setting up [LPIPS] perceptual loss: trunk [alex], v[0.1], spatial [off]
Loading model from: /usr/local/envs/nerf-tf115/lib/python3.7/site-packages/lpips/weights/v0.1/alex.pth
Setting up [LPIPS] perceptual loss: trunk [vgg], v[0.1], spatial [off]
Loading model from: /usr/local/envs/nerf-tf115/lib/python3.7/site-packages/lpips/weights/v0.1/vgg.pth

2026-04-16 20:05:03.711132: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcuda.so.1
2026-04-16 20:05:03.828109: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:983] succe

Trained Fern

In [ ]:
%cd /content/cg_nerf
!conda run -n nerf-tf115 python project_tools/render_eval_nerf.py --config nerf/course_configs/fern_t4_20min.txt --output_dir result/nerf/fern_trained --source trained --train_time_minutes 20

/content/cg_nerf
Loaded image data (378, 504, 3, 20) [378.         504.         407.56579161]
Loaded /content/cg_nerf/nerf/data/nerf_llff_data/fern 16.985296178676084 80.00209740336334
recentered (3, 5)
[[ 1.0000000e+00  0.0000000e+00  0.0000000e+00  1.4901161e-09]
 [ 0.0000000e+00  1.0000000e+00 -1.8730975e-09 -9.6857544e-09]
 [-0.0000000e+00  1.8730975e-09  1.0000000e+00  0.0000000e+00]]
Data:
(20, 3, 5) (20, 378, 504, 3) (20, 2)
HOLDOUT view is 12
MODEL 63 27 <class 'int'> <class 'int'> True
(?, 90) (?, 63) (?, 27)
MODEL 63 27 <class 'int'> <class 'int'> True
(?, 90) (?, 63) (?, 27)
Found ckpts ['/content/cg_nerf/nerf/logs/fern_t4_20min/model_005000.npy']
Reloading from /content/cg_nerf/nerf/logs/fern_t4_20min/model_005000.npy
Resetting step to 5001
Reloading fine from /content/cg_nerf/nerf/logs/fern_t4_20min/model_fine_005000.npy
Setting up [LPIPS] perceptual loss: trunk [alex], v[0.1], spatial [off]
Loading model from: /usr/local/envs/nerf-tf115/lib/python3.7/site-packages/lpips/w

download paper pre-trained model

In [ ]:
%cd /content/cg_nerf/nerf
!conda run -n nerf-tf115 bash download_example_weights.sh > /dev/null

/content/cg_nerf/nerf
--2026-04-17 05:34:37--  http://cseweb.ucsd.edu/~viscomp/projects/LF/papers/ECCV20/nerf/fern_example_weights.zip
Resolving cseweb.ucsd.edu (cseweb.ucsd.edu)... 132.239.8.30
Connecting to cseweb.ucsd.edu (cseweb.ucsd.edu)|132.239.8.30|:80... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://cseweb.ucsd.edu//~viscomp/projects/LF/papers/ECCV20/nerf/fern_example_weights.zip [following]
--2026-04-17 05:34:37--  https://cseweb.ucsd.edu//~viscomp/projects/LF/papers/ECCV20/nerf/fern_example_weights.zip
Connecting to cseweb.ucsd.edu (cseweb.ucsd.edu)|132.239.8.30|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 4430584 (4.2M) [application/zip]
Saving to: ‘fern_example_weights.zip’

     0K .......... .......... .......... .......... ..........  1%  932K 5s
    50K .......... .......... .......... .......... ..........  2% 1.83M 3s
   100K .......... .......... .......... .......... ..........  3%  140M 2s
   150K ......

In [ ]:
!find -name "model_*.npy"

./nerf/logs/lego_example/model_200000.npy
./nerf/logs/lego_example/model_fine_200000.npy
./nerf/logs/fern_example/model_200000.npy
./nerf/logs/fern_example/model_fine_200000.npy


Paper Lego

In [ ]:
%cd /content/cg_nerf
!conda run -n nerf-tf115 python project_tools/render_eval_nerf.py --config nerf/course_configs/lego_t4_20min.txt --ckpt logs/lego_example/model_200000.npy --output_dir result/nerf/lego_pretrained --source pretrained

/content/cg_nerf
MODEL 63 27 <class 'int'> <class 'int'> True
(?, 90) (?, 63) (?, 27)
MODEL 63 27 <class 'int'> <class 'int'> True
(?, 90) (?, 63) (?, 27)
Not ndc!
Found ckpts ['/content/cg_nerf/nerf/logs/lego_example/model_200000.npy']
Reloading from /content/cg_nerf/nerf/logs/lego_example/model_200000.npy
Resetting step to 200001
Reloading fine from /content/cg_nerf/nerf/logs/lego_example/model_fine_200000.npy
Setting up [LPIPS] perceptual loss: trunk [alex], v[0.1], spatial [off]
Loading model from: /usr/local/envs/nerf-tf115/lib/python3.7/site-packages/lpips/weights/v0.1/alex.pth
Setting up [LPIPS] perceptual loss: trunk [vgg], v[0.1], spatial [off]
Loading model from: /usr/local/envs/nerf-tf115/lib/python3.7/site-packages/lpips/weights/v0.1/vgg.pth

2026-04-17 05:42:48.754745: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcuda.so.1
2026-04-17 05:42:48.873961: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:983] succes

In [ ]:
/content/cg_nerf/nerf/logs/lego_example/model_fine_200000.npy

Paper Fern

In [ ]:
%cd /content/cg_nerf
!conda run -n nerf-tf115 python project_tools/render_eval_nerf.py --config nerf/course_configs/fern_t4_20min.txt --ckpt logs/fern_example/model_200000.npy --output_dir result/nerf/fern_pretrained  --source pretrained

/content/cg_nerf
Loaded image data (378, 504, 3, 20) [378.         504.         407.56579161]
Loaded /content/cg_nerf/nerf/data/nerf_llff_data/fern 16.985296178676084 80.00209740336334
recentered (3, 5)
[[ 1.0000000e+00  0.0000000e+00  0.0000000e+00  1.4901161e-09]
 [ 0.0000000e+00  1.0000000e+00 -1.8730975e-09 -9.6857544e-09]
 [-0.0000000e+00  1.8730975e-09  1.0000000e+00  0.0000000e+00]]
Data:
(20, 3, 5) (20, 378, 504, 3) (20, 2)
HOLDOUT view is 12
MODEL 63 27 <class 'int'> <class 'int'> True
(?, 90) (?, 63) (?, 27)
MODEL 63 27 <class 'int'> <class 'int'> True
(?, 90) (?, 63) (?, 27)
Found ckpts ['/content/cg_nerf/nerf/logs/fern_example/model_200000.npy']
Reloading from /content/cg_nerf/nerf/logs/fern_example/model_200000.npy
Resetting step to 200001
Reloading fine from /content/cg_nerf/nerf/logs/fern_example/model_fine_200000.npy
Setting up [LPIPS] perceptual loss: trunk [alex], v[0.1], spatial [off]
Loading model from: /usr/local/envs/nerf-tf115/lib/python3.7/site-packages/lpips/we

Savedata

In [ ]:
%cd /content/cg_nerf
from google.colab import drive
drive.mount('/content/drive')
!cp -r /content/cg_nerf/nerf/logs/* '/content/drive/My Drive/Colab Notebooks/CG-pj/nerf/logs/'
!cp -r /content/cg_nerf/result/* '/content/drive/My Drive/Colab Notebooks/CG-pj/result/'
# !cp -r /content/cg_nerf/DirectVoxGO/logs/* '/content/drive/My Drive/Colab Notebooks/CG-pj/DirectVoxGO/logs/'

/content/cg_nerf
Mounted at /content/drive


Edge-aware NeRF

load data

In [ ]:
%cd /content/cg_nerf/nerf
!mkdir -p data

from google.colab import drive
drive.mount('/content/drive')
!cp "/content/drive/My Drive/Colab Notebooks/CG-pj/dataset/nerf_example_data.zip" data
%cd data
!unzip -q nerf_example_data.zip
!ls data

%cd /content/cg_nerf
!cp -r "/content/drive/My Drive/Colab Notebooks/CG-pj/nerf/logs" ./nerf/
!cp -r "/content/drive/My Drive/Colab Notebooks/CG-pj/result" ./

Train lego-edge

In [ ]:
%cd /content/cg_nerf/nerf
!time conda run -n nerf-tf115 python run_nerf.py --config course_configs/lego_edge_alpha06.txt

Train fern-edge

In [ ]:
%cd /content/cg_nerf/nerf
!time conda run -n nerf-tf115 python run_nerf.py --config course_configs/fern_edge_alpha04.txt

Eval lego-edge

In [ ]:
%%bash
cd /content/cg_nerf
conda run -n nerf-tf115 python project_tools/render_eval_nerf.py \
  --config nerf/course_configs/lego_edge_alpha06.txt \
  --output_dir result/nerf/lego_edge_alpha06 \
  --source trained \
  --train_time_minutes 20


Eval fern-edge

In [ ]:
%%bash
cd /content/cg_nerf
conda run -n nerf-tf115 python project_tools/render_eval_nerf.py \
  --config nerf/course_configs/fern_edge_alpha04.txt \
  --output_dir result/nerf/fern_edge_alpha04 \
  --source trained \
  --train_time_minutes 20

Edge-Region Metrics

In [ ]:
%%bash
conda run -n nerf-tf115 python project_tools/eval_edge_regions.py --eval_dir result/nerf/lego_trained
conda run -n nerf-tf115 python project_tools/eval_edge_regions.py --eval_dir result/nerf/lego_edge_alpha06
conda run -n nerf-tf115 python project_tools/eval_edge_regions.py --eval_dir result/nerf/fern_trained
conda run -n nerf-tf115 python project_tools/eval_edge_regions.py --eval_dir result/nerf/fern_edge_alpha04

Aggregate Metrics

In [ ]:
%%bash
conda run -n nerf-tf115 python project_tools/aggregate_metrics.py \
  result/nerf/lego_trained/metrics.json \
  result/nerf/lego_edge_alpha06/metrics.json \
  result/nerf/fern_trained/metrics.json \
  result/nerf/fern_edge_alpha04/metrics.json \
  --out_csv result/nerf/edge_summary_metrics.csv

savedata

In [ ]:
%cd /content/cg_nerf
from google.colab import drive
drive.mount('/content/drive')
!cp -r nerf/logs/lego_edge_alpha06 '/content/drive/My Drive/Colab Notebooks/CG-pj/nerf/logs/'
!cp -r nerf/logs/fern_edge_alpha04 '/content/drive/My Drive/Colab Notebooks/CG-pj/nerf/logs/'
!cp -r result/nerf '/content/drive/My Drive/Colab Notebooks/CG-pj/result/'

# DVGO

In [ ]:
!rm -rf '/content/cg_nerf/'
!git clone https://github.com/LazyGH/cg_nerf.git
!pip install -q condacolab
import condacolab
condacolab.install()
%cd /content/cg_nerf
!mamba env create -f DirectVoxGO/environment_colab_legacy.yml
!conda run --no-capture-output -n dvgo-legacy pip install torch==1.12.1+cu113 torchvision==0.13.1+cu113 torchaudio==0.12.1 --extra-index-url https://download.pytorch.org/whl/cu113

!conda run -n dvgo-legacy python -V
!conda run --no-capture-output -n dvgo-legacy python -c "import torch; print('torch:', torch.__version__); print('cuda:', torch.version.cuda)"

!conda run --no-capture-output -n dvgo-legacy pip install --no-index torch_scatter -f https://data.pyg.org/whl/torch-1.12.0+cu113.html

Cloning into 'cg_nerf'...
remote: Enumerating objects: 314, done.
remote: Counting objects: 100% (314/314), done.
remote: Compressing objects: 100% (215/215), done.
remote: Total 314 (delta 130), reused 280 (delta 96), pack-reused 0 (from 0)
Receiving objects: 100% (314/314), 3.65 MiB | 9.62 MiB/s, done.
Resolving deltas: 100% (130/130), done.
⏬ Downloading https://github.com/jaimergp/miniforge/releases/download/24.11.2-1_colab/Miniforge3-colab-24.11.2-1_colab-Linux-x86_64.sh...
📦 Installing...
📌 Adjusting configuration...
🩹 Patching environment...
⏲ Done in 0:00:07
🔁 Restarting kernel...
/content/cg_nerf
Channels:
 - conda-forge
Platform: linux-64
Solving environment: \ | / - done


==> WARNING: A newer version of conda exists. <==
    current version: 24.11.2
    latest version: 26.3.2

Please update conda by running

    $ conda update -n base -c conda-forge conda



qt6-main-6.8.3       | 49.1 MB   | :   0% 0/1 [00:00<?, ?it/s]
libllvm21-21.1.0     | 42.3 MB   | :   0% 0/1 

In [ ]:
# !rm -rf '/content/cg_nerf/'
# !git clone https://github.com/LazyGH/cg_nerf.git

# %cd /content/cg_nerf
# !pip install ninja opencv-python-headless imageio imageio-ffmpeg lpips torch_efficient_distloss einops openmim mmcv-lite

# !pip uninstall -y torch torchvision
# !pip install torch==1.13.1+cu117 torchvision==0.14.1+cu117 --extra-index-url https://download.pytorch.org/whl/cu117

# %cd /content/cg_nerf
# !pip install ninja opencv-python-headless imageio imageio-ffmpeg lpips torch_efficient_distloss einops openmim mmcv-lite

In [ ]:
# import torch
# import os
# os.environ['TORCH'] = torch.__version__.split('+')[0]
# os.environ['CUDA'] = 'cpu' if torch.version.cuda is None else f"cu{torch.version.cuda.replace('.', '')}"

# # 4. Verify they were set
# print("TORCH:", os.environ['TORCH'])
# print("CUDA:", os.environ['CUDA'])

# !pip install torch_scatter -f https://data.pyg.org/whl/torch-${TORCH}+${CUDA}.html


TORCH: 2.11.0
CUDA: cu130
Looking in links: https://data.pyg.org/whl/torch-2.11.0+cu130.html


In [ ]:

%cd /content/cg_nerf/nerf
from google.colab import drive
drive.mount('/content/drive')

%cd /content/cg_nerf
!mkdir -p DirectVoxGO/data
!cp "/content/drive/My Drive/Colab Notebooks/CG-pj/dataset/nerf_example_data.zip" DirectVoxGO/data/
%cd /content/cg_nerf/DirectVoxGO/data
!unzip nerf_example_data.zip > /dev/null
!ls /content/cg_nerf/DirectVoxGO/data
# !cp -r nerf/data/nerf_synthetic DirectVoxGO/data/
# !cp -r nerf/data/nerf_llff_data DirectVoxGO/data/

/content/cg_nerf/nerf
Mounted at /content/drive
/content/cg_nerf
/content/cg_nerf/DirectVoxGO/data
nerf_example_data.zip  nerf_llff_data  nerf_synthetic
/content/cg_nerf/DirectVoxGO


ModuleNotFoundError: No module named 'torch_scatter'

In [ ]:
%cd /content/cg_nerf/DirectVoxGO
!conda run --no-capture-output -n dvgo-legacy python -c "from lib import dvgo; print('DVGO CUDA extension loaded successfully.')"

/content/cg_nerf/DirectVoxGO
Detected CUDA files, patching ldflags
Emitting ninja build file /root/.cache/torch_extensions/py38_cu113/render_utils_cuda/build.ninja...
Building extension module render_utils_cuda...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
[1/3] c++ -MMD -MF render_utils.o.d -DTORCH_EXTENSION_NAME=render_utils_cuda -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -isystem /usr/local/envs/dvgo-legacy/lib/python3.8/site-packages/torch/include -isystem /usr/local/envs/dvgo-legacy/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -isystem /usr/local/envs/dvgo-legacy/lib/python3.8/site-packages/torch/include/TH -isystem /usr/local/envs/dvgo-legacy/lib/python3.8/site-packages/torch/include/THC -isystem /usr/local/cuda/include -isystem /usr/local/envs/dvgo-legacy/include/python3.8 -D_GLIBCXX_USE_CXX11_ABI=

Train Test

In [ ]:
%cd /content/cg_nerf/DirectVoxGO
!time conda run -n dvgo-legacy python run.py --config configs/course/fern_t4_test.py

/content/cg_nerf/DirectVoxGO
Detected CUDA files, patching ldflags
Emitting ninja build file /root/.cache/torch_extensions/py38_cu113/adam_upd_cuda/build.ninja...
Building extension module adam_upd_cuda...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
ninja: no work to do.
Loading extension module adam_upd_cuda...
Detected CUDA files, patching ldflags
Emitting ninja build file /root/.cache/torch_extensions/py38_cu113/render_utils_cuda/build.ninja...
Building extension module render_utils_cuda...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
ninja: no work to do.
Loading extension module render_utils_cuda...
Detected CUDA files, patching ldflags
Emitting ninja build file /root/.cache/torch_extensions/py38_cu113/total_variation_cuda/build.ninja...
Building extension module total_variation_cuda...
Allowing ninja to set a default number of workers... (over

Train DVGO lego

In [ ]:
%cd /content/cg_nerf/DirectVoxGO
!time conda run -n dvgo-legacy python run.py --config configs/course/lego_t4_20min.py --i_tb 100

/content/cg_nerf/DirectVoxGO
Detected CUDA files, patching ldflags
Emitting ninja build file /root/.cache/torch_extensions/py38_cu113/adam_upd_cuda/build.ninja...
Building extension module adam_upd_cuda...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
ninja: no work to do.
Loading extension module adam_upd_cuda...
Detected CUDA files, patching ldflags
Emitting ninja build file /root/.cache/torch_extensions/py38_cu113/render_utils_cuda/build.ninja...
Building extension module render_utils_cuda...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
ninja: no work to do.
Loading extension module render_utils_cuda...
Detected CUDA files, patching ldflags
Emitting ninja build file /root/.cache/torch_extensions/py38_cu113/total_variation_cuda/build.ninja...
Building extension module total_variation_cuda...
Allowing ninja to set a default number of workers... (over

Train DVGO fern

In [ ]:
%cd /content/cg_nerf/DirectVoxGO
!time conda run -n dvgo-legacy python run.py --config configs/course/fern_t4_20min.py --i_tb 100

/content/cg_nerf/DirectVoxGO
Detected CUDA files, patching ldflags
Emitting ninja build file /root/.cache/torch_extensions/py38_cu113/adam_upd_cuda/build.ninja...
Building extension module adam_upd_cuda...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
ninja: no work to do.
Loading extension module adam_upd_cuda...
Detected CUDA files, patching ldflags
Emitting ninja build file /root/.cache/torch_extensions/py38_cu113/render_utils_cuda/build.ninja...
Building extension module render_utils_cuda...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
ninja: no work to do.
Loading extension module render_utils_cuda...
Detected CUDA files, patching ldflags
Emitting ninja build file /root/.cache/torch_extensions/py38_cu113/total_variation_cuda/build.ninja...
Building extension module total_variation_cuda...
Allowing ninja to set a default number of workers... (over

Tensorboard

In [ ]:
%load_ext tensorboard
%tensorboard --logdir /content/cg_nerf/DirectVoxGO/logs

DVGO Evaluation

Lego

In [ ]:
# %cd /content/cg_nerf
# !conda run -n dvgo-legacy python project_tools/render_eval_dvgo.py --config DirectVoxGO/configs/course/lego_t4_20min.py --output_dir result/dvgo/lego_trained --source traine--train_time_minutes 20

Fern

In [ ]:
%cd /content/cg_nerf
!conda run -n dvgo-legacy python project_tools/render_eval_dvgo.py --config DirectVoxGO/configs/course/fern_t4_20min.py --output_dir result/dvgo/fern_trained --source trained --train_time_minutes 20

/content/cg_nerf
Detected CUDA files, patching ldflags
Emitting ninja build file /root/.cache/torch_extensions/py38_cu113/render_utils_cuda/build.ninja...
Building extension module render_utils_cuda...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
ninja: no work to do.
Loading extension module render_utils_cuda...
Detected CUDA files, patching ldflags
Emitting ninja build file /root/.cache/torch_extensions/py38_cu113/total_variation_cuda/build.ninja...
Building extension module total_variation_cuda...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
ninja: no work to do.
Loading extension module total_variation_cuda...
No modifications detected for re-loaded extension module render_utils_cuda, skipping build step...
Loading extension module render_utils_cuda...
Detected CUDA files, patching ldflags
Emitting ninja build file /root/.cache/torch_extensions/p

Summary quantitative Results

In [14]:
%cd /content/cg_nerf
from google.colab import drive
drive.mount('/content/drive')
!cp -r "/content/drive/My Drive/Colab Notebooks/CG-pj/result/nerf" /content/cg_nerf/result

/content/cg_nerf
Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [15]:
%%bash
cd /content/cg_nerf
python project_tools/aggregate_metrics.py \
  result/nerf/lego_trained/metrics.json \
  result/nerf/fern_trained/metrics.json \
  result/nerf/lego_pretrained/metrics.json \
  result/nerf/fern_pretrained/metrics.json \
  result/dvgo/fern_trained/metrics.json \
  --out_csv result/summary_metrics.csv

In [17]:
%cd /content/cg_nerf
!cp result/summary_metrics.csv "/content/drive/My Drive/Colab Notebooks/CG-pj/result/"

Save data

In [ ]:
%cd /content/cg_nerf
from google.colab import drive
drive.mount('/content/drive')
!cp -r /content/cg_nerf/DirectVoxGO/logs/* "/content/drive/My Drive/Colab Notebooks/CG-pj/DirectVoxGO/logs/"
# !cp -r /content/cg_nerf/nerf/logs/* "/content/drive/My Drive/Colab Notebooks/CG-pj/nerf/logs/"
!cp -r /content/cg_nerf/result "/content/drive/My Drive/Colab Notebooks/CG-pj/result/"

/content/cg_nerf
Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
